name: flutter_components
description: "A new Flutter project."
version: 0.0.1
repository: https://github.com/serserm/flutter_components
homepage: https://github.com/serserm/flutter_components
issue_tracker: https://github.com/serserm/flutter_components/issues

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_components
      ios:
        default_package: flutter_components
      web:
        default_package: flutter_components
